CLEAN_DOCS:
  JINJA:
    JINJA_URL: "https://r.jina.ai/"
    JINJA_API_KEY: "[REDACTED]"
INTERNET_ARCHIVE:
  INTERNET_ARCHIVE_URL: "https://web.archive.org/"
  INTERNET_ARCHIVE_SAVE_URL: "https://web.archive.org/save/"
  INTERNET_ARCHIVE_S3_ACCESS_KEY: "[REDACTED]"
  INTERNET_ARCHIVE_S3_SECRET_KEY: "[REDACTED]"
MYSQL:
  HOST: "[REDACTED]"
  USER: "[REDACTED]"
  PORT: 3306
  PASSWORD: "[REDACTED]"
  DATABASE_NAME: "[REDACTED]"
  MYSQL_SCRIPT_FILE_PATH: ""
  INSERT_BATCH_SIZE: 20
  RAND_SEED: 420
SEARCH:
  API:
    GOOGLE_SEARCH_API_KEY: "[REDACTED]"
PRIVATE_FOLDER_PATHS:
  OUTPUT_FOLDER: "[REDACTED]"